### PR TITLE
the Myanmar TZ is now Asia/Yangon

### PR DESCRIPTION
**Pull request by krichprollsch**
see http://php.net/manual/en/timezones.asia.php
But it depends of the php version

### CODE REVIEW

**Comment by Taluu** [comment]
Hum then maybe the format of how eveything is registered is wrong, we shouldn't rely on a static ? Something that can change the value of this translation depending on the version...

**Comment by Taluu** [comment]
Another alternative (it's a bit dirty though) is to have multiple classes depending on a specific php version, and make an appropriate `class_alias`, but this is really dirty though...

**Comment by krichprollsch** [comment]
But the real TZ now is `Asia/Yangon`. There is no real reason to allow `Asia/Rangoon` anymore.
Should we really ensure the timezone returned by the lib is valid into the php list ?

Another point is the list into the `WindowsTimezone` class is partial... I don't know where the list come from.

**Comment by Taluu** [comment]
The list was made from several official links (check the class header). Merging into 1.0, as indeed it should not be php's version problem

**Pull request merged**
