### PR TITLE
check the attendee data format before use it

### PR DESCRIPTION
**Pull request by krichprollsch**
Sometimes, the `emailAddress` has no `address` /o\

### CODE REVIEW

**Comment by Taluu** [comment]
... when ? :o

**Comment by krichprollsch** [comment]
I have a user currently in this case, why? I don't know :/

**Review by Taluu — APPROVED** [review]

**Comment by Taluu** [comment]
Ah, office !

**Comment by krichprollsch** [comment]
ty @Taluu

**Pull request merged**
